### ISSUE TITLE
运行时出错

### ISSUE THREAD

**Issue by towonzhou** [Psli/ropencc#10]
$ uname -a
`Darwin TonyzhoudeMacBook-Air.local 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64`

$ opencc -v

```
Open Chinese Convert (OpenCC) Command Line Tool
Version 0.4.3

Author: BYVoid <byvoid@byvoid.com>
Bug Report: http://github.com/BYVoid/OpenCC/issues
```

ropencc (0.0.6)

```
require 'ropencc'

cc = Ropencc.open 'zhtw2zhcn_s.ini'
cc.convert '新年快樂'
```

```
/Users/tonyzhou/.rvm/gems/ruby-1.9.3-p125/gems/ffi-1.9.8/lib/ffi/library.rb:261:in `attach_function': Function 'opencc_convert_utf8_to_buffer' not found in [libopencc.dylib] (FFI::NotFoundError)
        from /Users/tonyzhou/.rvm/gems/ruby-1.9.3-p125/gems/ropencc-0.0.6/lib/ropencc.rb:11:in `<module:LibOpenCC>'
        from /Users/tonyzhou/.rvm/gems/ruby-1.9.3-p125/gems/ropencc-0.0.6/lib/ropencc.rb:6:in `<class:Ropencc>'
        from /Users/tonyzhou/.rvm/gems/ruby-1.9.3-p125/gems/ropencc-0.0.6/lib/ropencc.rb:5:in `<top (required)>'
        from /Users/tonyzhou/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:128:in `require'
        from /Users/tonyzhou/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from /Users/tonyzhou/.rvm/rubies/ruby-1.9.3-p125/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:39:in `require'
        from s2t.rb:9:in `<main>'
```

**Comment by emj365** [comment]
I got the same problem. Fixed it by upgrade opencc to 1.0.3
