### ISSUE TITLE
Could not open library 'libopencc.so': libopencc.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by swordray** [Psli/ropencc#11]
``` bash
# rails c
/usr/local/rvm/gems/ruby-2.2.2/gems/ffi-1.9.10/lib/ffi/library.rb:133:in `block in ffi_lib': Could not open library 'opencc': opencc: cannot open shared object file: No such file or directory. (LoadError)
Could not open library 'libopencc.so': libopencc.so: cannot open shared object file: No such file or directory
    from /usr/local/rvm/gems/ruby-2.2.2/gems/ffi-1.9.10/lib/ffi/library.rb:100:in `map'
    from /usr/local/rvm/gems/ruby-2.2.2/gems/ffi-1.9.10/lib/ffi/library.rb:100:in `ffi_lib'
    from /usr/local/rvm/gems/ruby-2.2.2/gems/ropencc-0.0.6/lib/ropencc.rb:8:in `<module:LibOpenCC>'
    from /usr/local/rvm/gems/ruby-2.2.2/gems/ropencc-0.0.6/lib/ropencc.rb:6:in `<class:Ropencc>'
    from /usr/local/rvm/gems/ruby-2.2.2/gems/ropencc-0.0.6/lib/ropencc.rb:5:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-2.2.2/gems/bundler-1.10.5/lib/bundler/runtime.rb:76:in `require'
    from /usr/local/rvm/gems/ruby-2.2.2/gems/bundler-1.10.5/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
    from /usr/local/rvm/gems/ruby-2.2.2/gems/bundler-1.10.5/lib/bundler/runtime.rb:72:in `each'
    from /usr/local/rvm/gems/ruby-2.2.2/gems/bundler-1.10.5/lib/bundler/runtime.rb:72:in `block in require'
    from /usr/local/rvm/gems/ruby-2.2.2/gems/bundler-1.10.5/lib/bundler/runtime.rb:61:in `each'
    from /usr/local/rvm/gems/ruby-2.2.2/gems/bundler-1.10.5/lib/bundler/runtime.rb:61:in `require'
    from /usr/local/rvm/gems/ruby-2.2.2/gems/bundler-1.10.5/lib/bundler.rb:134:in `require'
    from /opt/otaku/config/application.rb:7:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:141:in `require'
    from /usr/local/rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:141:in `require_application_and_environment!'
    from /usr/local/rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:67:in `console'
    from /usr/local/rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /usr/local/rvm/gems/ruby-2.2.2/gems/railties-4.2.2/lib/rails/commands.rb:17:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
```

``` bash
# opencc --version

Open Chinese Convert (OpenCC) Command Line Tool
Version: 1.0.3
```

``` bash
# bundle list ropencc
/usr/local/rvm/gems/ruby-2.2.2/gems/ropencc-0.0.6
```

``` bash
# ls /usr/lib/libopencc.so*
/usr/lib/libopencc.so    /usr/lib/libopencc.so.1.0.0
/usr/lib/libopencc.so.1  /usr/lib/libopencc.so.2
```

**Comment by swordray** [comment]
Solved by `echo "/usr/local/lib" >> /etc/ld.so.conf`

**Comment by echan00** [comment]
@swordray Do you mind explaining what your solution does? I have the same error but circumstances are different (I am pushing a OpenCC buildpack to heroku)

**Comment by swordray** [comment]
> @swordray Do you mind explaining what your solution does? I have the same error but circumstances are different (I am pushing a OpenCC buildpack to heroku)

@echan00 sorry buddy, I can't remember that and the solution is not needed right now. I think I was adding `/usr/local/lib` to shared library path (LD_LIBRARY_PATH).
